---
# tasks file for EPEL - RHEL
- name: Setup for EPEL repository
  block:
    - name: Install EPEL
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_facts['distribution']['major_version'] }}.noarch.rpm
        state: latest

  become: true
